from decimal import Decimal, ROUND_HALF_UP
from NSE_get_data_from_ESDL import *
from NG_input_data import *


def ng_run_all_functions(capex_h2_station_variable,
                         capex_h2_pipeline_variable,
                         capex_h2_boiler_variable,
                         capex_ng_boiler_variable,
                         opex_h2_boiler_variable,
                         network_costs_h2_variable,
                         h2_price_variable,
                         hwi_price_variable,
                         opex_ng_boiler_variable,
                         network_costs_ng_variable,
                         carbon_permits_variable,
                         ng_price_variable,
                         ng_tax_variable,
                         inflation_variable,
                         loan_percentage_variable,
                         loan_interest_rate_variable,
                         income_tax_rate_variable,
                         wacc_variable,
                         lifetime_investment_variable):    
    

    # Here we import all the functions from the working file
    from ipynb.fs.defs.NG_offtaker_working_file import (construct_calendar_year_list, 
                                                        construct_business_case_year_list, 
                                                        construct_operations_years_list, 
                                                        construct_decomissioning_years_list, 
                                                        construction_phase,
                                                        operational_phase,
                                                        decommissioning_phase,
                                                        taxes_and_profits_part1,
                                                        debt_and_loan_part1,
                                                        avoided_debt_and_loan_part1,
                                                        taxes_and_profits_part2,
                                                        debt_and_loan_part2,
                                                        project_reserves,
                                                        equity_funding,
                                                        present_value_cashflows,
                                                        cumulative_equity_and_debt_cashflows,
                                                        discounted_cashflows_for_levelized_cost,
                                                        levelized_cost_and_revenues,
                                                        project_kpi,
                                                        equity_kpi,
                                                        output_kpi)



    construct_calendar_year_list(lifetime_investment_variable)
    construct_business_case_year_list(lifetime_investment_variable)
    construct_operations_years_list(lifetime_investment_variable)
    construct_decomissioning_years_list(lifetime_investment_variable)

    construction_phase(capex_h2_station_variable, 
                       capex_h2_pipeline_variable,
                       capex_h2_boiler_variable, 
                       capex_ng_boiler_variable,
                       inflation_variable,
                       lifetime_investment_variable)

    operational_phase(opex_h2_boiler_variable,
                      network_costs_h2_variable,
                      h2_price_variable,
                      hwi_price_variable,
                      opex_ng_boiler_variable,
                      network_costs_ng_variable,
                      carbon_permits_variable,
                      ng_price_variable,
                      ng_tax_variable,
                      inflation_variable,
                      lifetime_investment_variable)

    decommissioning_phase(capex_h2_boiler_variable,
                          capex_ng_boiler_variable,
                          inflation_variable,
                          lifetime_investment_variable)

    taxes_and_profits_part1(capex_h2_station_variable,
                            capex_h2_pipeline_variable,
                            capex_h2_boiler_variable,
                            capex_ng_boiler_variable,
                            opex_h2_boiler_variable,
                            network_costs_h2_variable,
                            h2_price_variable,
                            hwi_price_variable,
                            opex_ng_boiler_variable,
                            network_costs_ng_variable,
                            carbon_permits_variable,
                            ng_price_variable,
                            ng_tax_variable,
                            inflation_variable,
                            lifetime_investment_variable)

    debt_and_loan_part1(capex_h2_station_variable,
                        capex_h2_pipeline_variable,
                        capex_h2_boiler_variable,
                        inflation_variable,
                        loan_percentage_variable,
                        loan_interest_rate_variable,
                        lifetime_investment_variable)
    
    avoided_debt_and_loan_part1(capex_ng_boiler_variable,
                                inflation_variable,
                                loan_percentage_variable,
                                loan_interest_rate_variable,
                                lifetime_investment_variable)

    taxes_and_profits_part2(capex_h2_station_variable,
                            capex_h2_pipeline_variable,
                            capex_h2_boiler_variable,
                            capex_ng_boiler_variable,
                            opex_h2_boiler_variable,
                            network_costs_h2_variable,
                            h2_price_variable,
                            hwi_price_variable,
                            opex_ng_boiler_variable,
                            network_costs_ng_variable,
                            carbon_permits_variable,
                            ng_price_variable,
                            ng_tax_variable,
                            inflation_variable,
                            loan_percentage_variable,
                            loan_interest_rate_variable,
                            income_tax_rate_variable,
                            lifetime_investment_variable)

    debt_and_loan_part2(capex_h2_station_variable,
                        capex_h2_pipeline_variable,
                        capex_h2_boiler_variable,
                        capex_ng_boiler_variable,
                        opex_h2_boiler_variable,
                        network_costs_h2_variable,
                        h2_price_variable,
                        hwi_price_variable,
                        opex_ng_boiler_variable,
                        network_costs_ng_variable,
                        carbon_permits_variable,
                        ng_price_variable,
                        ng_tax_variable,
                        inflation_variable,
                        loan_percentage_variable,
                        loan_interest_rate_variable,
                        income_tax_rate_variable,
                        lifetime_investment_variable)

    project_reserves(capex_h2_station_variable,
                     capex_h2_pipeline_variable,
                     capex_h2_boiler_variable, 
                     inflation_variable,
                     lifetime_investment_variable)

    equity_funding(capex_h2_station_variable,
                   capex_h2_pipeline_variable,
                   capex_h2_boiler_variable,
                   capex_ng_boiler_variable,
                   opex_h2_boiler_variable,
                   network_costs_h2_variable,
                   h2_price_variable,
                   hwi_price_variable,
                   opex_ng_boiler_variable,
                   network_costs_ng_variable,
                   carbon_permits_variable,
                   ng_price_variable,
                   ng_tax_variable,
                   inflation_variable,
                   loan_percentage_variable,
                   loan_interest_rate_variable,
                   income_tax_rate_variable,
                   lifetime_investment_variable)

    present_value_cashflows(capex_h2_station_variable,
                            capex_h2_pipeline_variable,
                            capex_h2_boiler_variable,
                            capex_ng_boiler_variable,
                            opex_h2_boiler_variable,
                            network_costs_h2_variable,
                            h2_price_variable,
                            hwi_price_variable,
                            opex_ng_boiler_variable,
                            network_costs_ng_variable,
                            carbon_permits_variable,
                            ng_price_variable,
                            ng_tax_variable,
                            inflation_variable,
                            loan_percentage_variable,
                            loan_interest_rate_variable,
                            income_tax_rate_variable,
                            wacc_variable,
                            lifetime_investment_variable)

    cumulative_equity_and_debt_cashflows(capex_h2_station_variable,
                                         capex_h2_pipeline_variable,
                                         capex_h2_boiler_variable,
                                         capex_ng_boiler_variable,
                                         opex_h2_boiler_variable,
                                         network_costs_h2_variable,
                                         h2_price_variable,
                                         hwi_price_variable,
                                         opex_ng_boiler_variable,
                                         network_costs_ng_variable,
                                         carbon_permits_variable,
                                         ng_price_variable,
                                         ng_tax_variable,
                                         inflation_variable,
                                         loan_percentage_variable,
                                         loan_interest_rate_variable,
                                         income_tax_rate_variable,
                                         lifetime_investment_variable)

    discounted_cashflows_for_levelized_cost(capex_h2_station_variable,
                                            capex_h2_pipeline_variable,
                                            capex_h2_boiler_variable,
                                            capex_ng_boiler_variable,
                                            opex_h2_boiler_variable,
                                            network_costs_h2_variable,
                                            h2_price_variable,
                                            hwi_price_variable,
                                            opex_ng_boiler_variable,
                                            network_costs_ng_variable,
                                            carbon_permits_variable,
                                            ng_price_variable,
                                            ng_tax_variable,
                                            inflation_variable,
                                            loan_percentage_variable,
                                            loan_interest_rate_variable,
                                            income_tax_rate_variable,
                                            wacc_variable,
                                            lifetime_investment_variable)

    levelized_cost_and_revenues(capex_h2_station_variable,
                                capex_h2_pipeline_variable,
                                capex_h2_boiler_variable,
                                capex_ng_boiler_variable,
                                opex_h2_boiler_variable,
                                network_costs_h2_variable,
                                h2_price_variable,
                                hwi_price_variable,
                                opex_ng_boiler_variable,
                                network_costs_ng_variable,
                                carbon_permits_variable,
                                ng_price_variable,
                                ng_tax_variable,
                                inflation_variable,
                                loan_percentage_variable,
                                loan_interest_rate_variable,
                                income_tax_rate_variable,
                                wacc_variable,
                                lifetime_investment_variable)


    project_kpi(capex_h2_station_variable,
                capex_h2_pipeline_variable,
                capex_h2_boiler_variable,
                capex_ng_boiler_variable,
                opex_h2_boiler_variable,
                network_costs_h2_variable,
                h2_price_variable,
                hwi_price_variable,
                opex_ng_boiler_variable,
                network_costs_ng_variable,
                carbon_permits_variable,
                ng_price_variable,
                ng_tax_variable,
                inflation_variable,
                loan_percentage_variable,
                loan_interest_rate_variable,
                income_tax_rate_variable,
                wacc_variable,
                lifetime_investment_variable)

    equity_kpi(capex_h2_station_variable,
               capex_h2_pipeline_variable,
               capex_h2_boiler_variable,
               capex_ng_boiler_variable,
               opex_h2_boiler_variable,
               network_costs_h2_variable,
               h2_price_variable,
               hwi_price_variable,
               opex_ng_boiler_variable,
               network_costs_ng_variable,
               carbon_permits_variable,
               ng_price_variable,
               ng_tax_variable,
               inflation_variable,
               loan_percentage_variable,
               loan_interest_rate_variable,
               income_tax_rate_variable,
               wacc_variable,
               lifetime_investment_variable)

    output_kpi(capex_h2_station_variable,
               capex_h2_pipeline_variable,
               capex_h2_boiler_variable,
               capex_ng_boiler_variable,
               opex_h2_boiler_variable,
               network_costs_h2_variable,
               h2_price_variable,
               hwi_price_variable,
               opex_ng_boiler_variable,
               network_costs_ng_variable,
               carbon_permits_variable,
               ng_price_variable,
               ng_tax_variable,
               inflation_variable,
               loan_percentage_variable,
               loan_interest_rate_variable,
               income_tax_rate_variable,
               wacc_variable,
               lifetime_investment_variable)