import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def run_levelized_breakdown_scenarios(runner_module, working_module, input_data_module, parameter_dict_name):
    """
    Loops through macro scenarios, reads the raw input file text, dynamically injects 
    the active scenario indices, and returns the compiled levelized breakdown comparison.

    parameter_dict_name should be a string!
    """
    macro_scenarios = ["pessimistic", "most_likely", "optimistic"]
    scen_dfs = []
    
   
    # 1. Read the raw python text directly from the input module file path
    file_path = input_data_module.__file__
    with open(file_path, 'r') as f:
        code_lines = f.readlines()
        
    for scen_name in macro_scenarios:
        target_idx = input_data_module.Scenario_mapping[scen_name]
        
        # 2. Filter out the hardcoded default assignments at the top of the file
        # Here we remove the active scenario name and active index from the input data file
        # This will allow us to loop over the different scenarios
        clean_code = []
        for line in code_lines:
            stripped = line.strip()
            if stripped.startswith("active_scenario_name =") or stripped.startswith("active_index ="):
                continue
            clean_code.append(line)
            
        # 3. Inject our loop's active scenario variables at the very top of the script execution
        clean_code.insert(0, f"active_scenario_name = '{scen_name}'\n")
        clean_code.insert(1, f"active_index = {target_idx}\n")
        
        # 4. Execute the script text inside an isolated temporary context dictionary
        # We use this to 
        sandbox_context = {}
        exec("".join(clean_code), globals(), sandbox_context)
        
        # 5. Extract the pristine parameter dictionary generated by the file logic
        # Change here the parameters according to the scenario that you run
        # e.g., el_parameters to run el_scenario, owf_parameters to run owf_scenario
        # probably better to add this as parameter to the function to be adjusted automatically
        scen_params = sandbox_context[parameter_dict_name]

        # 6. Run the business case for this scenario and get the details dictionary (i.e. the saved intermediate dfs of each function)
        # _, _, _, is a conventional way of saying 'I don't need this value'
        # we cannot just say 'details = ..' because run_business_case returns 4 object as a tuple, that we need to unpack
        _, _, _, details = runner_module.run_business_case(working_module, scen_params, return_details=True)

        # 7. Extract the scenario-specific discounted cashflows      
        df_discounted_cashflows_for_levelized_cost = details['discounted_cashflows_for_levelized_cost']
        
        # 8. Calculated the levelized cost and revenues
        df_scen = working_module.levelized_cost_and_revenues(df_discounted_cashflows_for_levelized_cost,
                                                             **scen_params)
        
        # 9. Format column headers for side-by-side merging
        formatted_name = scen_name.capitalize() if scen_name != 'most_likely' else 'Base'
        df_scen = df_scen.rename(columns={
            'cost': f'Cost ({formatted_name})', 
            'revenues': f'Revenue ({formatted_name})'
        })

        scen_dfs.append(df_scen)
        
    # 10. Merge all scenarios side-by-side on row index names
    df_master_breakdown = pd.concat(scen_dfs, axis=1)
    
    return df_master_breakdown





def clean_label(text):
    """Formats raw database index strings into legend titles."""
    text = text.replace("_", " ")
    text = text.capitalize()
    text = text.replace("Capex", "CAPEX").replace("Opex", "OPEX")
    text = text.replace("Ppa", "PPA").replace("Hwi", "HWI").replace("H2", "H₂").replace("ppa", "PPA")
    return text




def plot_scenario_breakdown(df_master, unit_label='€/MWh (levelized)'):
    """
    Dynamically renders an itemized, stacked macro-scenario comparison chart
    compatible with any business case data schema (Electrolyser, OWF, etc.).
    """
    # 1. Establish the universal core color profile sheet
    color_mapping = {
        'CAPEX': 'blue', 'OPEX': 'orange', 'Purchase electricity PPA': 'yellow',
        'Purchase electricity grid': 'gold', 'Electricity grid connection': 'mediumorchid',
        'H₂ storage costs': 'burlywood', 'Stack replacement': 'lightblue', 
        'Decommissioning': '#FF1493', 'Interest costs': 'purple', 'Contingency': 'brown',
        'Tax expenses': 'grey', 
        'H₂ revenues': 'green', 'HWI revenues': 'lightgreen',  
        'Revenues PPA': 'green', 'Revenues market': 'lightgreen',
        'Profits': 'limegreen', 'Unprofitable gap': 'red'
    }
    
    # 2. Extract the actual variables present in the DataFrame dynamically
    # Ensures compatibility with different modules (e.g., EL, OWF)
    raw_rows = df_master.index.tolist()
    clean_columns = []

    for row in raw_rows:
        clean_text = clean_label(row)
        clean_columns.append(clean_text)
    
    # 3. Restructure and Transpose the DataFrame to prepare for the axis layout
    df_plot = df_master.T.copy()
    df_plot.columns = clean_columns
    
    # Scenarios mapping matches our dynamic generation headers
    scenarios = ['Pessimistic', 'Base', 'Optimistic']
    
    # Initialize the subplots side by side
    # Creates a window containing 1 row and 3 columns of subplots
    fig, axes = plt.subplots(1, 3, figsize=(15, 6), sharey=True)
    
    # 4. Loop through the subplots and stack the metrics
    for ax, scen in zip(axes, scenarios):
        # Target the specific Cost and Revenue columns for this iteration's scenario
        scen_cols = [f'Cost ({scen})', f'Revenue ({scen})']
        df_sub = df_plot.loc[scen_cols]
        
        # Rename row indices from text headers to minimal axis labels ('Costs', 'Revenues')
        df_sub.index = ['Costs', 'Revenues']
        
        # Draw the basic structural stacked bar chart
        df_sub.plot(kind='bar', stacked=True, ax=ax, rot=0, legend=False)
        
        # Add labels
        ax.set_xlabel(scen, fontsize=12, labelpad=10)
        if ax == axes[0]:
            ax.set_ylabel(unit_label, fontsize=12)
            
        # 5. Stylize every individual color block dynamically based on the mapped variable
        for i, container in enumerate(ax.containers):
            col_name = clean_columns[i]
            
            for patch in container:
                if col_name in ['Unprofitable gap', 'Profits']:
                    # Special boundary styling for empty margin columns
                    edge_color = 'red' if col_name == 'Unprofitable gap' else 'limegreen'
                    patch.set_edgecolor(edge_color)
                    patch.set_linestyle('--')
                    patch.set_linewidth(2)
                    patch.set_facecolor('white')
                else:
                    # Dynamically look up the mapped color, fallback to gray for unknown items
                    patch.set_color(color_mapping.get(col_name, 'lightgray'))

    # 6. Global formatting overrides
    fig.text(0.35, 0.98, 'Levelized Costs and Revenues', ha='center', va='bottom', fontsize=14)
    
    # Generate a unified, clean deduplicated legend matching only the active rows
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)
    
    # Dynamic chart ceiling adjustments based on maximum compiled asset value
    max_val = df_plot.sum(axis=1).max()
    y_limit = int(np.ceil(max_val / 100.0) * 100) # Rounds up to the nearest 100
    
    for ax in axes:
        ax.grid(True, which='major', axis='y', linestyle='-', alpha=0.6)
        ax.set_ylim(0, y_limit)
        
    plt.tight_layout(rect=[0, 0, 0.82, 0.95])
    plt.show()